name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create a text file
        run: |
          echo "This is a sample text file" > ./path/to/your/build/directory/sample.txt
          
      - name: Upload text file artifact
        uses: actions/upload-artifact@v4
        with:
          name: text-file-artifact
          path: ./path/to/your/build/directory/sample.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
